In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [2]:

# fetch dataset 
dt= pd.read_csv("heart.csv")

In [3]:
dt

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [4]:
dt.shape

(918, 12)

In [5]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [6]:
dt.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [7]:
dt.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [8]:
dt.tail()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [9]:
dt.describe(include = "all")

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
count,918.000000,918,918,918.000000,918.000000,918.000000,918,918.000000,918,918.000000,918,918.000000
unique,NaN,2,4,NaN,NaN,NaN,3,NaN,2,NaN,3,NaN
top,NaN,M,ASY,NaN,NaN,NaN,Normal,NaN,N,NaN,Flat,NaN
freq,NaN,725,496,NaN,NaN,NaN,552,NaN,547,NaN,460,NaN
mean,53.510893,NaN,NaN,132.396514,198.799564,0.233115,NaN,136.809368,NaN,0.887364,NaN,0.553377
std,9.432617,NaN,NaN,18.514154,109.384145,0.423046,NaN,25.460334,NaN,1.066570,NaN,0.497414
min,28.000000,NaN,NaN,0.000000,0.000000,0.000000,NaN,60.000000,NaN,-2.600000,NaN,0.000000
25%,47.000000,NaN,NaN,120.000000,173.250000,0.000000,NaN,120.000000,NaN,0.000000,NaN,0.000000
50%,54.000000,NaN,NaN,130.000000,223.000000,0.000000,NaN,138.000000,NaN,0.600000,NaN,1.000000
75%,60.000000,NaN,NaN,140.000000,267.000000,0.000000,NaN,156.000000,NaN,1.500000,NaN,1.000000
max,77.000000,NaN,NaN,200.000000,603.000000,1.000000,NaN,202.000000,NaN,6.200000,NaN,1.000000

In [10]:
dt.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [11]:
dt.shape

(918, 12)

In [12]:
dt.nunique()

Age                50
Sex                 2
ChestPainType       4
RestingBP          67
Cholesterol       222
FastingBS           2
RestingECG          3
MaxHR             119
ExerciseAngina      2
Oldpeak            53
ST_Slope            3
HeartDisease        2
dtype: int64

In [13]:
dt.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='object')

In [14]:
cat_col =  dt.select_dtypes(include ='object').columns
cat_col

Index(['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope'], dtype='object')

In [15]:
dt["ChestPainType"].unique()

array(['ATA', 'NAP', 'ASY', 'TA'], dtype=object)

In [16]:
range(dt["ChestPainType"].nunique())

range(0, 4)

In [17]:
for col in cat_col:
    print(col)
    print((dt[col].unique()),list(range(dt[col].nunique())))
    dt[col].replace((dt[col].unique()),range(dt[col].nunique()),inplace = True)
    print('*'*90)
    print()

Sex
['M' 'F'] [0, 1]
******************************************************************************************

ChestPainType
['ATA' 'NAP' 'ASY' 'TA'] [0, 1, 2, 3]
******************************************************************************************

RestingECG
['Normal' 'ST' 'LVH'] [0, 1, 2]
******************************************************************************************

ExerciseAngina
['N' 'Y'] [0, 1]
******************************************************************************************

ST_Slope
['Up' 'Flat' 'Down'] [0, 1, 2]
******************************************************************************************

C:\Users\hp\AppData\Local\Temp\ipykernel_11080\958717912.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dt[col].replace((dt[col].unique()),range(dt[col].nunique()),inplace = True)
C:\Users\hp\AppData\Local\Temp\ipykernel_11080\958717912.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dt[col].replace((dt[col].unique()),range(dt[col].nunique()),inplace = True)

In [18]:
dt

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,0,0,140,289,0,0,172,0,0.0,0,0
1,49,1,1,160,180,0,0,156,0,1.0,1,1
2,37,0,0,130,283,0,1,98,0,0.0,0,0
3,48,1,2,138,214,0,0,108,1,1.5,1,1
4,54,0,1,150,195,0,0,122,0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,0,3,110,264,0,0,132,0,1.2,1,1
914,68,0,2,144,193,1,0,141,0,3.4,1,1
915,57,0,2,130,131,0,0,115,1,1.2,1,1
916,57,1,0,130,236,0,2,174,0,0.0,1,1
917,38,0,1,138,175,0,0,173,0,0.0,0,0

In [19]:
dt["Cholesterol"].value_counts()

Cholesterol
0      172
254     11
220     10
223     10
204      9
      ...
353      1
278      1
157      1
176      1
131      1
Name: count, Length: 222, dtype: int64

In [20]:
np.nan

nan

In [21]:
dt["Cholesterol"].replace(0,np.nan, inplace = True)

C:\Users\hp\AppData\Local\Temp\ipykernel_11080\1466004283.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dt["Cholesterol"].replace(0,np.nan, inplace = True)

In [22]:
from sklearn.impute import  KNNImputer
imputer = KNNImputer(n_neighbors=3)
after_impute = imputer.fit_transform(dt)
dt = pd.DataFrame(after_impute,columns=dt.columns)

In [23]:
dt['Cholesterol'].isna().sum()

np.int64(0)

In [24]:
count = 0

for i in dt['Cholesterol']:
    if i == 0:
        count+=1
print(count)

0

In [25]:
dt['RestingBP'][dt['RestingBP']==0]

449    0.0
Name: RestingBP, dtype: float64

In [26]:
from sklearn.impute import KNNImputer
dt['RestingBP'].replace(0,np.nan,inplace= True)
imputer = KNNImputer(n_neighbors=3)
after_impute = imputer.fit_transform(dt)
dt=pd.DataFrame(after_impute,columns=dt.columns)

C:\Users\hp\AppData\Local\Temp\ipykernel_11080\131574445.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dt['RestingBP'].replace(0,np.nan,inplace= True)

In [27]:
dt['RestingBP'].unique()

array([140., 160., 130., 138., 150., 120., 110., 136., 115., 100., 124.,
       113., 125., 145., 112., 132., 118., 170., 142., 190., 135., 180.,
       108., 155., 128., 106.,  92., 200., 122.,  98., 105., 133.,  95.,
        80., 137., 185., 165., 126., 152., 116., 144., 154., 134., 104.,
       139., 131., 141., 178., 146., 158., 123., 102.,  96., 143., 172.,
       156., 114., 127., 101., 174.,  94., 148., 117., 192., 129., 164.])

In [28]:
dt['RestingBP'].isnull().sum()

np.int64(0)

In [29]:
dt['Oldpeak']

0      0.0
1      1.0
2      0.0
3      1.5
4      0.0
      ...
913    1.2
914    3.4
915    1.2
916    0.0
917    0.0
Name: Oldpeak, Length: 918, dtype: float64

In [30]:
withoutoldpeak = dt.columns
withoutoldpeak = withoutoldpeak.drop('Oldpeak')
dt[withoutoldpeak] = dt[withoutoldpeak].astype('int32')

In [31]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int32
 1   Sex             918 non-null    int32
 2   ChestPainType   918 non-null    int32
 3   RestingBP       918 non-null    int32
 4   Cholesterol     918 non-null    int32
 5   FastingBS       918 non-null    int32
 6   RestingECG      918 non-null    int32
 7   MaxHR           918 non-null    int32
 8   ExerciseAngina  918 non-null    int32
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    int32
 11  HeartDisease    918 non-null    int32
dtypes: float64(1), int32(11)
memory usage: 46.7 KB

<h1>Visualisation</h1>

In [32]:
dt.sample()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
582,69,0,2,122,216,1,2,84,1,0.0,1,1

In [33]:
dt.corr()['HeartDisease'].sort_values()

MaxHR            -0.400421
Sex              -0.305445
RestingECG        0.061011
Cholesterol       0.101263
RestingBP         0.118333
FastingBS         0.267291
Age               0.282039
Oldpeak           0.403951
ChestPainType     0.459017
ExerciseAngina    0.494282
ST_Slope          0.558771
HeartDisease      1.000000
Name: HeartDisease, dtype: float64

In [34]:
import plotly.express as px

In [35]:
px.line(dt.corr()['HeartDisease'].sort_values())

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'variable=HeartDisease<br>index=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'HeartDisease',
              'line': {'color': '#636efa', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'HeartDisease',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': array(['MaxHR', 'Sex', 'RestingECG', 'Cholesterol', 'RestingBP', 'FastingBS',
                          'Age', 'Oldpeak', 'ChestPainType', 'ExerciseAngina', 'ST_Slope',
                          'HeartDisease'], dtype=object),
              'xaxis': 'x',
              'y': {'bdata': ('ovJeb36g2b9OojLVaIzTv7rAvnHYPK' ... 'R471Ci3z+tvkcfc+HhPwAAAAAAAPA/'),
                    'dtype': 'f8'},
              'yaxis': 'y'}],
    'layout': {'legend': {'title': {'text': 'variable'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'index'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'value'}}}
})

In [36]:
px.sunburst(dt,path=['HeartDisease','Age'])

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'branchvalues': 'total',
              'domain': {'x': [0.0, 1.0], 'y': [0.0, 1.0]},
              'hovertemplate': 'labels=%{label}<br>count=%{value}<br>parent=%{parent}<br>id=%{id}<extra></extra>',
              'ids': array(['0/40', '1/49', '0/37', '1/48', '0/54', '0/39', '0/45', '1/37', '0/48',
                            '1/58', '0/42', '1/38', '0/43', '1/60', '1/36', '0/44', '0/49', '1/44',
                            '0/36', '0/53', '0/52', '0/51', '1/53', '0/56', '1/54', '1/41', '0/32',
                            '1/65', '0/41', '0/35', '1/43', '0/59', '0/50', '1/50', '1/47', '1/31',
                            '1/52', '1/46', '1/57', '1/55', '0/46', '1/32', '0/55', '1/63', '1/56',
                            '1/66', '1/40', '0/57', '0/34', '0/47', '0/38', '1/33', '1/59', '1/34',
                            '0/58', '0/61', '0/29', '0/62', '0/31', '1/35', '0/28', '0/30', '1/39',
                            '1/51', '0/33', '1/45', '0/60', '1/61', '1/62', '0/65', '1/74', '1/68',
                            '1/42', '0/72', '1/64', '1/69', '1/67', '1/73', '1/70', '0/66', '0/63',
                            '0/74', '1/77', '1/72', '1/75', '0/64', '1/76', '0/68', '1/71', '0/75',
                            '0/69', '0/67', '0/71', '0/70', '0/76', '0', '1'], dtype=object),
              'labels': array(['40', '49', '37', '48', '54', '39', '45', '37', '48', '58', '42', '38',
                               '43', '60', '36', '44', '49', '44', '36', '53', '52', '51', '53', '56',
                               '54', '41', '32', '65', '41', '35', '43', '59', '50', '50', '47', '31',
                               '52', '46', '57', '55', '46', '32', '55', '63', '56', '66', '40', '57',
                               '34', '47', '38', '33', '59', '34', '58', '61', '29', '62', '31', '35',
                               '28', '30', '39', '51', '33', '45', '60', '61', '62', '65', '74', '68',
                               '42', '72', '64', '69', '67', '73', '70', '66', '63', '74', '77', '72',
                               '75', '64', '76', '68', '71', '75', '69', '67', '71', '70', '76', '0',
                               '1'], dtype=object),
              'name': '',
              'parents': array(['0', '1', '0', '1', '0', '0', '0', '1', '0', '1', '0', '1', '0', '1',
                                '1', '0', '0', '1', '0', '0', '0', '0', '1', '0', '1', '1', '0', '1',
                                '0', '0', '1', '0', '0', '1', '1', '1', '1', '1', '1', '1', '0', '1',
                                '0', '1', '1', '1', '1', '0', '0', '0', '0', '1', '1', '1', '0', '0',
                                '0', '0', '0', '1', '0', '0', '1', '1', '0', '1', '0', '1', '1', '0',
                                '1', '1', '1', '0', '1', '1', '1', '1', '1', '0', '0', '0', '1', '1',
                                '1', '0', '1', '0', '1', '0', '0', '0', '0', '0', '0', '', ''],
                               dtype=object),
              'type': 'sunburst',
              'values': {'bdata': ('BwALAAoADwAcAA0ADwABABAAHAAPAA' ... 'EABAACAAEAAwADAAMAAQABAJoB/AE='),
                         'dtype': 'i2'}}],
    'layout': {'legend': {'tracegroupgap': 0}, 'margin': {'t': 60}, 'template': '...'}
})

In [37]:
px.histogram(dt,x='Age',color='HeartDisease')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'bingroup': 'x',
              'hovertemplate': 'HeartDisease=0<br>Age=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '0',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '0',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('KAAAACUAAAA2AAAAJwAAAC0AAAA2AA' ... 'AAOAAAADgAAAA3AAAAKQAAACYAAAA='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'},
             {'bingroup': 'x',
              'hovertemplate': 'HeartDisease=1<br>Age=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '1',
              'marker': {'color': '#EF553B', 'pattern': {'shape': ''}},
              'name': '1',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('MQAAADAAAAAlAAAAOgAAADEAAAAmAA' ... 'A5AAAALQAAAEQAAAA5AAAAOQAAAA=='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'title': {'text': 'HeartDisease'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'Age'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'count'}}}
})

In [38]:
px.pie(dt,names='HeartDisease',title='Percentage of HeartDisease')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'domain': {'x': [0.0, 1.0], 'y': [0.0, 1.0]},
              'hovertemplate': 'HeartDisease=%{label}<extra></extra>',
              'labels': {'bdata': ('AAAAAAEAAAAAAAAAAQAAAAAAAAAAAA' ... 'AAAAEAAAABAAAAAQAAAAEAAAAAAAAA'),
                         'dtype': 'i4'},
              'legendgroup': '',
              'name': '',
              'showlegend': True,
              'type': 'pie'}],
    'layout': {'legend': {'tracegroupgap': 0}, 'template': '...', 'title': {'text': 'Percentage of HeartDisease'}}
})

In [39]:
px.histogram(dt,x='Sex',color='HeartDisease')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'bingroup': 'x',
              'hovertemplate': 'HeartDisease=0<br>Sex=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '0',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '0',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('AAAAAAAAAAAAAAAAAAAAAAEAAAAAAA' ... 'AAAAAAAAAAAAABAAAAAAAAAAAAAAA='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'},
             {'bingroup': 'x',
              'hovertemplate': 'HeartDisease=1<br>Sex=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '1',
              'marker': {'color': '#EF553B', 'pattern': {'shape': ''}},
              'name': '1',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('AQAAAAEAAAAAAAAAAAAAAAAAAAAAAA' ... 'ABAAAAAAAAAAAAAAAAAAAAAQAAAA=='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'title': {'text': 'HeartDisease'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'Sex'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'count'}}}
})

In [40]:
px.histogram(dt,x='ChestPainType',color='HeartDisease')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'bingroup': 'x',
              'hovertemplate': 'HeartDisease=0<br>ChestPainType=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '0',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '0',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('AAAAAAAAAAABAAAAAQAAAAAAAAAAAA' ... 'AAAAAAAAAAAAAAAAAAAAAAAAEAAAA='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'},
             {'bingroup': 'x',
              'hovertemplate': 'HeartDisease=1<br>ChestPainType=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '1',
              'marker': {'color': '#EF553B', 'pattern': {'shape': ''}},
              'name': '1',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('AQAAAAIAAAACAAAAAAAAAAIAAAACAA' ... 'ACAAAAAwAAAAIAAAACAAAAAAAAAA=='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'title': {'text': 'HeartDisease'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'ChestPainType'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'count'}}}
})

In [41]:
px.sunburst(dt,path=['HeartDisease','RestingBP'])

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'branchvalues': 'total',
              'domain': {'x': [0.0, 1.0], 'y': [0.0, 1.0]},
              'hovertemplate': 'labels=%{label}<br>count=%{value}<br>parent=%{parent}<br>id=%{id}<extra></extra>',
              'ids': array(['0/140', '1/160', '0/130', '1/138', '0/150', '0/120', '0/110', '1/140',
                            '1/136', '0/115', '1/110', '1/100', '1/120', '0/100', '0/124', '1/150',
                            '0/113', '0/125', '1/145', '1/125', '1/130', '0/112', '0/160', '1/112',
                            '0/132', '1/118', '1/170', '0/142', '0/190', '1/135', '1/180', '0/108',
                            '0/145', '1/115', '1/155', '1/128', '0/135', '0/180', '0/170', '1/106',
                            '1/92', '1/200', '1/122', '0/122', '0/98', '0/105', '0/133', '1/95',
                            '1/105', '0/155', '0/80', '1/137', '1/185', '1/165', '1/132', '1/142',
                            '0/126', '1/133', '0/152', '1/116', '0/138', '1/124', '1/144', '0/154',
                            '1/134', '0/104', '1/139', '0/128', '1/131', '0/134', '1/152', '1/126',
                            '1/154', '1/141', '0/131', '1/178', '1/146', '1/158', '0/106', '0/136',
                            '0/123', '1/102', '1/96', '0/139', '1/143', '1/104', '1/172', '1/156',
                            '0/118', '1/190', '0/114', '1/127', '0/101', '1/174', '1/108', '0/156',
                            '0/94', '0/148', '0/178', '1/117', '1/192', '1/123', '0/129', '0/102',
                            '0/172', '0/146', '1/148', '1/114', '1/164', '0', '1'], dtype=object),
              'labels': array(['140', '160', '130', '138', '150', '120', '110', '140', '136', '115',
                               '110', '100', '120', '100', '124', '150', '113', '125', '145', '125',
                               '130', '112', '160', '112', '132', '118', '170', '142', '190', '135',
                               '180', '108', '145', '115', '155', '128', '135', '180', '170', '106',
                               '92', '200', '122', '122', '98', '105', '133', '95', '105', '155', '80',
                               '137', '185', '165', '132', '142', '126', '133', '152', '116', '138',
                               '124', '144', '154', '134', '104', '139', '128', '131', '134', '152',
                               '126', '154', '141', '131', '178', '146', '158', '106', '136', '123',
                               '102', '96', '139', '143', '104', '172', '156', '118', '190', '114',
                               '127', '101', '174', '108', '156', '94', '148', '178', '117', '192',
                               '123', '129', '102', '172', '146', '148', '114', '164', '0', '1'],
                              dtype=object),
              'name': '',
              'parents': array(['0', '1', '0', '1', '0', '0', '0', '1', '1', '0', '1', '1', '1', '0',
                                '0', '1', '0', '0', '1', '1', '1', '0', '0', '1', '0', '1', '1', '0',
                                '0', '1', '1', '0', '0', '1', '1', '1', '0', '0', '0', '1', '1', '1',
                                '1', '0', '0', '0', '0', '1', '1', '0', '0', '1', '1', '1', '1', '1',
                                '0', '1', '0', '1', '0', '1', '1', '0', '1', '0', '1', '0', '1', '0',
                                '1', '1', '1', '1', '0', '1', '1', '1', '0', '0', '0', '1', '1', '0',
                                '1', '1', '1', '1', '0', '1', '0', '1', '0', '1', '1', '0', '0', '0',
                                '0', '1', '1', '1', '0', '0', '0', '0', '1', '1', '1', '', ''],
                               dtype=object),
              'type': 'sunburst',
              'values': {'bdata': ('NAAiAEIABwAZAE0AGgA4AAoABAAgAA' ... 'ABAAEAAQACAAEAAQABAAEAAQCaAfwB'),
                         'dtype': 'i2'}}],
    'layout': {'legend': {'tracegroupgap': 0}, 'margin': {'t': 60}, 'template': '...'}
})

In [42]:
px.histogram(dt,x='FastingBS',color='HeartDisease')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'bingroup': 'x',
              'hovertemplate': 'HeartDisease=0<br>FastingBS=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '0',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '0',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' ... 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAA='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'},
             {'bingroup': 'x',
              'hovertemplate': 'HeartDisease=1<br>FastingBS=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '1',
              'marker': {'color': '#EF553B', 'pattern': {'shape': ''}},
              'name': '1',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' ... 'AAAAAAAAAAAAEAAAAAAAAAAAAAAA=='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'title': {'text': 'HeartDisease'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'FastingBS'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'count'}}}
})

In [43]:
px.violin(dt,x='HeartDisease',y='MaxHR',color='HeartDisease')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'alignmentgroup': 'True',
              'box': {'visible': False},
              'hovertemplate': 'HeartDisease=%{x}<br>MaxHR=%{y}<extra></extra>',
              'legendgroup': '0',
              'marker': {'color': '#636efa'},
              'name': '0',
              'offsetgroup': '0',
              'orientation': 'v',
              'scalegroup': 'True',
              'showlegend': True,
              'type': 'violin',
              'x': {'bdata': ('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' ... 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAA='),
                    'dtype': 'i4'},
              'x0': ' ',
              'xaxis': 'x',
              'y': {'bdata': ('rAAAAGIAAAB6AAAAqgAAAKoAAACOAA' ... 'AAowAAAKkAAACmAAAAtgAAAK0AAAA='),
                    'dtype': 'i4'},
              'y0': ' ',
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'box': {'visible': False},
              'hovertemplate': 'HeartDisease=%{x}<br>MaxHR=%{y}<extra></extra>',
              'legendgroup': '1',
              'marker': {'color': '#EF553B'},
              'name': '1',
              'offsetgroup': '1',
              'orientation': 'v',
              'scalegroup': 'True',
              'showlegend': True,
              'type': 'violin',
              'x': {'bdata': ('AQAAAAEAAAABAAAAAQAAAAEAAAABAA' ... 'ABAAAAAQAAAAEAAAABAAAAAQAAAA=='),
                    'dtype': 'i4'},
              'x0': ' ',
              'xaxis': 'x',
              'y': {'bdata': ('nAAAAGwAAACCAAAAYwAAAIwAAACmAA' ... 'B7AAAAhAAAAI0AAABzAAAArgAAAA=='),
                    'dtype': 'i4'},
              'y0': ' ',
              'yaxis': 'y'}],
    'layout': {'legend': {'title': {'text': 'HeartDisease'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'violinmode': 'overlay',
               'xaxis': {'anchor': 'y',
                         'categoryarray': [0, 1],
                         'categoryorder': 'array',
                         'domain': [0.0, 1.0],
                         'title': {'text': 'HeartDisease'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'MaxHR'}}}
})

In [44]:
px.histogram(dt,x='ST_Slope', color='HeartDisease')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'bingroup': 'x',
              'hovertemplate': 'HeartDisease=0<br>ST_Slope=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '0',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '0',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' ... 'AAAAAAAAIAAAAAAAAAAAAAAAAAAAA='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'},
             {'bingroup': 'x',
              'hovertemplate': 'HeartDisease=1<br>ST_Slope=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '1',
              'marker': {'color': '#EF553B', 'pattern': {'shape': ''}},
              'name': '1',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('AQAAAAEAAAABAAAAAQAAAAEAAAABAA' ... 'ABAAAAAQAAAAEAAAABAAAAAQAAAA=='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'title': {'text': 'HeartDisease'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'ST_Slope'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'count'}}}
})

In [45]:
px.histogram(dt,x='ExerciseAngina',color='HeartDisease')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'bingroup': 'x',
              'hovertemplate': 'HeartDisease=0<br>ExerciseAngina=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '0',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '0',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' ... 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAA='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'},
             {'bingroup': 'x',
              'hovertemplate': 'HeartDisease=1<br>ExerciseAngina=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '1',
              'marker': {'color': '#EF553B', 'pattern': {'shape': ''}},
              'name': '1',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('AAAAAAEAAAABAAAAAQAAAAEAAAAAAA' ... 'ABAAAAAAAAAAAAAAABAAAAAAAAAA=='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'title': {'text': 'HeartDisease'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'ExerciseAngina'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'count'}}}
})